import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/features/sideBar/sideBar";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster"


const Satoshi = localFont({
  src: "./fonts/Satoshi-Variable.ttf",
  weight: "100 900",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Satoshi.className} antialiased`}
      >
      
        <SideBar> {children}</SideBar>
        <Toaster  />
       
      </body>
    </html>
  );
}
